/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class casio_serial_SerialPort */

#ifndef _Included_casio_serial_SerialPort
#define _Included_casio_serial_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     casio_serial_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_casio_serial_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     casio_serial_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_casio_serial_SerialPort_close
  (JNIEnv *, jobject);

/*
 * Class:     casio_serial_SerialPort
 * Method:    IOCTLVIB
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_casio_serial_SerialPort_IOCTLVIB
  (JNIEnv *, jobject, jint );

#ifdef __cplusplus
}
#endif
#endif
